<?php

namespace Database\Seeders;
use DB;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        //Populate charts table
        DB::table('charts')->insert([
            [
                    "id" => 1,
                    "county" => "Baringo",
                    "total_population" => 666763,
                    "male_population" => 336322,
                    "female_population" => 330428,
                    "households" => 142518,
                    "av_hh_size" => 5,
                    "land_area" => 10976,
                    "population_density" => 61,
                    "population_in_2009" => 555561,
                    "population_change" => 111202,
                    "intersex_population" => 13,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 2,
                    "county" => "Bomet",
                    "total_population" => 875689,
                    "male_population" => 434287,
                    "female_population" => 441379,
                    "households" => 187641,
                    "av_hh_size" => 5,
                    "land_area" => 2531,
                    "population_density" => 346,
                    "population_in_2009" => 724186,
                    "population_change" => 151503,
                    "intersex_population" => 23,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 3,
                    "county" => "Bungoma",
                    "total_population" => 1670570,
                    "male_population" => 812146,
                    "female_population" => 858389,
                    "households" => 358796,
                    "av_hh_size" => 5,
                    "land_area" => 3024,
                    "population_density" => 552,
                    "population_in_2009" => 1630934,
                    "population_change" => 39636,
                    "intersex_population" => 35,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 4,
                    "county" => "Busia",
                    "total_population" => 893681,
                    "male_population" => 426252,
                    "female_population" => 467401,
                    "households" => 198152,
                    "av_hh_size" => 5,
                    "land_area" => 1696,
                    "population_density" => 527,
                    "population_in_2009" => 488075,
                    "population_change" => 405606,
                    "intersex_population" => 28,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 5,
                    "county" => "Elgeyo-Marakwet",
                    "total_population" => 454480,
                    "male_population" => 227317,
                    "female_population" => 227151,
                    "households" => 99861,
                    "av_hh_size" => 5,
                    "land_area" => 3032,
                    "population_density" => 150,
                    "population_in_2009" => 369998,
                    "population_change" => 84482,
                    "intersex_population" => 12,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 6,
                    "county" => "Embu",
                    "total_population" => 608599,
                    "male_population" => 304208,
                    "female_population" => 304367,
                    "households" => 182743,
                    "av_hh_size" => 3,
                    "land_area" => 2821,
                    "population_density" => 216,
                    "population_in_2009" => 516212,
                    "population_change" => 92387,
                    "intersex_population" => 24,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 7,
                    "county" => "Garissa",
                    "total_population" => 841353,
                    "male_population" => 458975,
                    "female_population" => 382344,
                    "households" => 141394,
                    "av_hh_size" => 6,
                    "land_area" => 44736,
                    "population_density" => 19,
                    "population_in_2009" => 623060,
                    "population_change" => 218293,
                    "intersex_population" => 34,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 8,
                    "county" => "Homa Bay",
                    "total_population" => 1131950,
                    "male_population" => 539560,
                    "female_population" => 592367,
                    "households" => 262036,
                    "av_hh_size" => 4,
                    "land_area" => 3153,
                    "population_density" => 359,
                    "population_in_2009" => 963794,
                    "population_change" => 168156,
                    "intersex_population" => 23,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 9,
                    "county" => "Isiolo",
                    "total_population" => 268002,
                    "male_population" => 139510,
                    "female_population" => 128483,
                    "households" => 58072,
                    "av_hh_size" => 5,
                    "land_area" => 25350,
                    "population_density" => 11,
                    "population_in_2009" => 143294,
                    "population_change" => 124708,
                    "intersex_population" => 9,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 10,
                    "county" => "Kajiado",
                    "total_population" => 1117840,
                    "male_population" => 557098,
                    "female_population" => 560704,
                    "households" => 316179,
                    "av_hh_size" => 4,
                    "land_area" => 21871,
                    "population_density" => 51,
                    "population_in_2009" => 687312,
                    "population_change" => 430528,
                    "intersex_population" => 38,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 11,
                    "county" => "Kakamega",
                    "total_population" => 1867579,
                    "male_population" => 897133,
                    "female_population" => 970406,
                    "households" => 433207,
                    "av_hh_size" => 4,
                    "land_area" => 3020,
                    "population_density" => 618,
                    "population_in_2009" => 1660651,
                    "population_change" => 206928,
                    "intersex_population" => 40,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 12,
                    "county" => "Kericho",
                    "total_population" => 901777,
                    "male_population" => 450751,
                    "female_population" => 451008,
                    "households" => 206036,
                    "av_hh_size" => 4,
                    "land_area" => 2436,
                    "population_density" => 370,
                    "population_in_2009" => 758339,
                    "population_change" => 143438,
                    "intersex_population" => 28,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 13,
                    "county" => "Kiambu",
                    "total_population" => 2417735,
                    "male_population" => 1187146,
                    "female_population" => 1230454,
                    "households" => 795241,
                    "av_hh_size" => 3,
                    "land_area" => 2539,
                    "population_density" => 952,
                    "population_in_2009" => 1623282,
                    "population_change" => 794453,
                    "intersex_population" => 135,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 14,
                    "county" => "Kilifi",
                    "total_population" => 1453787,
                    "male_population" => 704089,
                    "female_population" => 749673,
                    "households" => 298472,
                    "av_hh_size" => 5,
                    "land_area" => 12540,
                    "population_density" => 116,
                    "population_in_2009" => 1109735,
                    "population_change" => 344052,
                    "intersex_population" => 25,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 15,
                    "county" => "Kirinyaga",
                    "total_population" => 610411,
                    "male_population" => 302011,
                    "female_population" => 308369,
                    "households" => 204188,
                    "av_hh_size" => 3,
                    "land_area" => 1478,
                    "population_density" => 413,
                    "population_in_2009" => 528054,
                    "population_change" => 82357,
                    "intersex_population" => 31,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 16,
                    "county" => "Kisii",
                    "total_population" => 1266860,
                    "male_population" => 605784,
                    "female_population" => 661038,
                    "households" => 308054,
                    "av_hh_size" => 4,
                    "land_area" => 1323,
                    "population_density" => 958,
                    "population_in_2009" => 1152282,
                    "population_change" => 114578,
                    "intersex_population" => 38,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 17,
                    "county" => "Kisumu",
                    "total_population" => 1155574,
                    "male_population" => 560942,
                    "female_population" => 594609,
                    "households" => 300745,
                    "av_hh_size" => 4,
                    "land_area" => 2085,
                    "population_density" => 554,
                    "population_in_2009" => 968909,
                    "population_change" => 186665,
                    "intersex_population" => 23,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 18,
                    "county" => "Kitui",
                    "total_population" => 1136187,
                    "male_population" => 549003,
                    "female_population" => 587151,
                    "households" => 262942,
                    "av_hh_size" => 4,
                    "land_area" => 30430,
                    "population_density" => 37,
                    "population_in_2009" => 1012709,
                    "population_change" => 123478,
                    "intersex_population" => 33,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 19,
                    "county" => "Kwale",
                    "total_population" => 866820,
                    "male_population" => 425121,
                    "female_population" => 441681,
                    "households" => 173176,
                    "av_hh_size" => 5,
                    "land_area" => 8267,
                    "population_density" => 105,
                    "population_in_2009" => 649931,
                    "population_change" => 216889,
                    "intersex_population" => 18,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 20,
                    "county" => "Laikipia",
                    "total_population" => 518580,
                    "male_population" => 259440,
                    "female_population" => 259102,
                    "households" => 149271,
                    "av_hh_size" => 3,
                    "land_area" => 9532,
                    "population_density" => 54,
                    "population_in_2009" => 399227,
                    "population_change" => 119353,
                    "intersex_population" => 18,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 21,
                    "county" => "Lamu",
                    "total_population" => 143920,
                    "male_population" => 76103,
                    "female_population" => 67813,
                    "households" => 37963,
                    "av_hh_size" => 4,
                    "land_area" => 6253,
                    "population_density" => 23,
                    "population_in_2009" => 101539,
                    "population_change" => 42381,
                    "intersex_population" => 4,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 22,
                    "county" => "Machakos",
                    "total_population" => 1421932,
                    "male_population" => 710707,
                    "female_population" => 711191,
                    "households" => 402466,
                    "av_hh_size" => 4,
                    "land_area" => 6043,
                    "population_density" => 235,
                    "population_in_2009" => 1098584,
                    "population_change" => 323348,
                    "intersex_population" => 34,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 23,
                    "county" => "Makueni",
                    "total_population" => 987653,
                    "male_population" => 489691,
                    "female_population" => 497942,
                    "households" => 244669,
                    "av_hh_size" => 4,
                    "land_area" => 8170,
                    "population_density" => 121,
                    "population_in_2009" => 884527,
                    "population_change" => 103126,
                    "intersex_population" => 20,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 24,
                    "county" => "Mandera",
                    "total_population" => 867457,
                    "male_population" => 434976,
                    "female_population" => 432444,
                    "households" => 125763,
                    "av_hh_size" => 7,
                    "land_area" => 25940,
                    "population_density" => 33,
                    "population_in_2009" => 1025756,
                    "population_change" => 158299,
                    "intersex_population" => 37,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 25,
                    "county" => "Marsabit",
                    "total_population" => 459785,
                    "male_population" => 243548,
                    "female_population" => 216219,
                    "households" => 77495,
                    "av_hh_size" => 6,
                    "land_area" => 70944,
                    "population_density" => 6,
                    "population_in_2009" => 291166,
                    "population_change" => 168619,
                    "intersex_population" => 18,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 26,
                    "county" => "Meru",
                    "total_population" => 1545714,
                    "male_population" => 767698,
                    "female_population" => 777975,
                    "households" => 426360,
                    "av_hh_size" => 4,
                    "land_area" => 7006,
                    "population_density" => 221,
                    "population_in_2009" => 1356301,
                    "population_change" => 189413,
                    "intersex_population" => 41,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 27,
                    "county" => "Migori",
                    "total_population" => 1116436,
                    "male_population" => 536187,
                    "female_population" => 580214,
                    "households" => 240168,
                    "av_hh_size" => 5,
                    "land_area" => 2614,
                    "population_density" => 427,
                    "population_in_2009" => 917170,
                    "population_change" => 199266,
                    "intersex_population" => 35,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 28,
                    "county" => "Mombasa",
                    "total_population" => 1208333,
                    "male_population" => 610257,
                    "female_population" => 598046,
                    "households" => 378422,
                    "av_hh_size" => 3,
                    "land_area" => 220,
                    "population_density" => 5495,
                    "population_in_2009" => 939370,
                    "population_change" => 268963,
                    "intersex_population" => 30,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 29,
                    "county" => "Murang'a",
                    "total_population" => 1056640,
                    "male_population" => 523940,
                    "female_population" => 532669,
                    "households" => 318105,
                    "av_hh_size" => 3,
                    "land_area" => 2524,
                    "population_density" => 419,
                    "population_in_2009" => 942581,
                    "population_change" => 114059,
                    "intersex_population" => 31,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 30,
                    "county" => "Nairobi",
                    "total_population" => 4397073,
                    "male_population" => 2192452,
                    "female_population" => 2204376,
                    "households" => 1506888,
                    "av_hh_size" => 3,
                    "land_area" => 704,
                    "population_density" => 6247,
                    "population_in_2009" => 3138369,
                    "population_change" => 1258704,
                    "intersex_population" => 245,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 31,
                    "county" => "Nakuru",
                    "total_population" => 2162202,
                    "male_population" => 1077272,
                    "female_population" => 1084835,
                    "households" => 616046,
                    "av_hh_size" => 4,
                    "land_area" => 7462,
                    "population_density" => 290,
                    "population_in_2009" => 1603325,
                    "population_change" => 558877,
                    "intersex_population" => 95,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 32,
                    "county" => "Nandi",
                    "total_population" => 885711,
                    "male_population" => 441259,
                    "female_population" => 444430,
                    "households" => 199426,
                    "av_hh_size" => 4,
                    "land_area" => 2856,
                    "population_density" => 310,
                    "population_in_2009" => 752965,
                    "population_change" => 132746,
                    "intersex_population" => 22,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 33,
                    "county" => "Narok",
                    "total_population" => 1157873,
                    "male_population" => 579042,
                    "female_population" => 578805,
                    "households" => 241125,
                    "av_hh_size" => 5,
                    "land_area" => 17950,
                    "population_density" => 65,
                    "population_in_2009" => 850920,
                    "population_change" => 306953,
                    "intersex_population" => 26,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 34,
                    "county" => "Nyamira",
                    "total_population" => 605576,
                    "male_population" => 290907,
                    "female_population" => 314656,
                    "households" => 150669,
                    "av_hh_size" => 4,
                    "land_area" => 897,
                    "population_density" => 675,
                    "population_in_2009" => 598252,
                    "population_change" => 7324,
                    "intersex_population" => 13,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 35,
                    "county" => "Nyandarua",
                    "total_population" => 638289,
                    "male_population" => 315022,
                    "female_population" => 323247,
                    "households" => 179686,
                    "av_hh_size" => 4,
                    "land_area" => 3286,
                    "population_density" => 194,
                    "population_in_2009" => 596268,
                    "population_change" => 42021,
                    "intersex_population" => 20,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 36,
                    "county" => "Nyeri",
                    "total_population" => 759164,
                    "male_population" => 374288,
                    "female_population" => 384845,
                    "households" => 248050,
                    "av_hh_size" => 3,
                    "land_area" => 3325,
                    "population_density" => 228,
                    "population_in_2009" => 693558,
                    "population_change" => 65606,
                    "intersex_population" => 31,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 37,
                    "county" => "Samburu",
                    "total_population" => 310327,
                    "male_population" => 156774,
                    "female_population" => 153546,
                    "households" => 65910,
                    "av_hh_size" => 5,
                    "land_area" => 21065,
                    "population_density" => 15,
                    "population_in_2009" => 223947,
                    "population_change" => 86380,
                    "intersex_population" => 7,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 38,
                    "county" => "Siaya",
                    "total_population" => 993183,
                    "male_population" => 471669,
                    "female_population" => 521496,
                    "households" => 250698,
                    "av_hh_size" => 4,
                    "land_area" => 2530,
                    "population_density" => 393,
                    "population_in_2009" => 842304,
                    "population_change" => 150879,
                    "intersex_population" => 18,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 39,
                    "county" => "Taita Taveta",
                    "total_population" => 340671,
                    "male_population" => 173337,
                    "female_population" => 167327,
                    "households" => 96429,
                    "av_hh_size" => 4,
                    "land_area" => 17152,
                    "population_density" => 20,
                    "population_in_2009" => 284657,
                    "population_change" => 56014,
                    "intersex_population" => 7,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 40,
                    "county" => "Tana River",
                    "total_population" => 315943,
                    "male_population" => 158550,
                    "female_population" => 157391,
                    "households" => 68242,
                    "av_hh_size" => 5,
                    "land_area" => 37951,
                    "population_density" => 8,
                    "population_in_2009" => 240075,
                    "population_change" => 75868,
                    "intersex_population" => 2,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 41,
                    "county" => "Tharaka-Nithi",
                    "total_population" => 393177,
                    "male_population" => 193764,
                    "female_population" => 199406,
                    "households" => 109860,
                    "av_hh_size" => 4,
                    "land_area" => 2564,
                    "population_density" => 153,
                    "population_in_2009" => 365330,
                    "population_change" => 27847,
                    "intersex_population" => 7,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 42,
                    "county" => "Trans Nzoia",
                    "total_population" => 990341,
                    "male_population" => 489107,
                    "female_population" => 501206,
                    "households" => 223808,
                    "av_hh_size" => 4,
                    "land_area" => 2495,
                    "population_density" => 397,
                    "population_in_2009" => 818757,
                    "population_change" => 171584,
                    "intersex_population" => 28,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 43,
                    "county" => "Turkana",
                    "total_population" => 926976,
                    "male_population" => 478087,
                    "female_population" => 448868,
                    "households" => 164519,
                    "av_hh_size" => 6,
                    "land_area" => 68233,
                    "population_density" => 14,
                    "population_in_2009" => 855399,
                    "population_change" => 71577,
                    "intersex_population" => 21,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 44,
                    "county" => "Uasin Gishu",
                    "total_population" => 1163186,
                    "male_population" => 580269,
                    "female_population" => 582889,
                    "households" => 304943,
                    "av_hh_size" => 4,
                    "land_area" => 3392,
                    "population_density" => 343,
                    "population_in_2009" => 894179,
                    "population_change" => 269007,
                    "intersex_population" => 28,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 45,
                    "county" => "Vihiga",
                    "total_population" => 590013,
                    "male_population" => 283678,
                    "female_population" => 306323,
                    "households" => 143365,
                    "av_hh_size" => 4,
                    "land_area" => 564,
                    "population_density" => 1047,
                    "population_in_2009" => 554622,
                    "population_change" => 35391,
                    "intersex_population" => 12,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 46,
                    "county" => "Wajir",
                    "total_population" => 781263,
                    "male_population" => 415374,
                    "female_population" => 365840,
                    "households" => 127932,
                    "av_hh_size" => 6,
                    "land_area" => 56773,
                    "population_density" => 14,
                    "population_in_2009" => 661941,
                    "population_change" => 119322,
                    "intersex_population" => 49,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ,[
                    "id" => 47,
                    "county" => "West Pokot",
                    "total_population" => 621241,
                    "male_population" => 307013,
                    "female_population" => 314213,
                    "households" => 116182,
                    "av_hh_size" => 5,
                    "land_area" => 9123,
                    "population_density" => 68,
                    "population_in_2009" => 512690,
                    "population_change" => 108551,
                    "intersex_population" => 15,
                    "created_at" => NULL,
                    "updated_at" => NULL]
            ]);
            
    }
}
